%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(auth_on_register_pb).
-define(auth_on_register_pb, true).

-define(auth_on_register_pb_gpb_version, "4.21.5").

-ifndef('EVENTSSIDECAR.V1.AUTHONREGISTER_PB_H').
-define('EVENTSSIDECAR.V1.AUTHONREGISTER_PB_H', true).
-record('eventssidecar.v1.AuthOnRegister',
    % = 1, optional
    {
        timestamp = undefined :: auth_on_register_pb:'google.protobuf.Timestamp'() | undefined,
        % = 2, optional
        mountpoint = <<>> :: unicode:chardata() | undefined,
        % = 3, optional
        client_id = <<>> :: unicode:chardata() | undefined,
        % = 4, optional
        peer_addr = <<>> :: unicode:chardata() | undefined,
        % = 5, optional, 32 bits
        peer_port = 0 :: integer() | undefined,
        % = 6, optional
        username = <<>> :: unicode:chardata() | undefined,
        % = 7, optional
        clean_session = false :: boolean() | 0 | 1 | undefined
    }
).
-endif.

-ifndef('GOOGLE.PROTOBUF.TIMESTAMP_PB_H').
-define('GOOGLE.PROTOBUF.TIMESTAMP_PB_H', true).
-record('google.protobuf.Timestamp',
    % = 1, optional, 64 bits
    {
        seconds = 0 :: integer() | undefined,
        % = 2, optional, 32 bits
        nanos = 0 :: integer() | undefined
    }
).
-endif.

-endif.
