%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.1

-ifndef(event_request_pb).
-define(event_request_pb, true).

-define(event_request_pb_gpb_version, "4.21.1").

-ifndef('WEBHOOK.V1BETA1.EVENTREQUEST_PB_H').
-define('WEBHOOK.V1BETA1.EVENTREQUEST_PB_H', true).
-record('webhook.v1beta1.EventRequest',
    % = 1, optional
    {event = undefined :: event_request_pb:'google.protobuf.Any'() | undefined}
).
-endif.

-ifndef('GOOGLE.PROTOBUF.ANY_PB_H').
-define('GOOGLE.PROTOBUF.ANY_PB_H', true).
-record('google.protobuf.Any',
    % = 1, optional
    {
        type_url = <<>> :: unicode:chardata() | undefined,
        % = 2, optional
        value = <<>> :: iodata() | undefined
    }
).
-endif.

-ifndef('GOOGLE.PROTOBUF.EMPTY_PB_H').
-define('GOOGLE.PROTOBUF.EMPTY_PB_H', true).
-record('google.protobuf.Empty', {}).
-endif.

-endif.
