%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(registration_failure_reason_pb).
-define(registration_failure_reason_pb, true).

-define(registration_failure_reason_pb_gpb_version, "4.21.5").

-endif.
