image: "erlang"

services:
  - postgres:9.2-alpine
  - mysql:5.6
  - redis
  - memcached
  - mongo

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - plts
    - plts_base

variables:
  POSTGRES_DB: vmq_test_database
  POSTGRES_USER: vmq_test_user
  POSTGRES_PASSWORD: "vmq_test_password"
  POSTGRES_HOST_AUTH_METHOD: trust
  MYSQL_DATABASE: "vmq_test_database"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

stages:
  - test
  - release

test:
  stage: test
  before_script:
    - apt-get update -y && apt-get install -y libsnappy-dev default-mysql-client
    - mysql -e "CREATE USER 'vmq_test_user' IDENTIFIED BY 'vmq_test_password';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'vmq_test_user';" -uroot
    - epmd -daemon
  script:
    - ./rebar3 as all_tests do dialyzer, eunit, ct

docker-release:
  stage: release
  script:
    - >
      docker build
      -t artifactory-gojek.golabs.io:6555/$CI_PROJECT_NAME:latest
      -t artifactory-gojek.golabs.io:6555/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
      -f docker/Dockerfile .
    - docker push artifactory-gojek.golabs.io:6555/$CI_PROJECT_NAME:latest
    - docker push artifactory-gojek.golabs.io:6555/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  tags:
    - docker
    - docker_artifactory
