version: '3'

services:
  redis-sentinel:
    image: bitnami/redis-sentinel:5.0
    volumes:
      - redis-sentinel_data:/bitnami
  redis:
    image: bitnami/redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
    ports:
      - "26379:26379"
volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local